export const metricNames = {
  httpRequestsTotal: "http_requests_total",
  httpRequestErrorsTotal: "http_request_errors_total",
  httpRequestDurationMs: "http_request_duration_ms",
  auditEventsTotal: "audit_events_total",
  validationErrorsTotal: "validation_errors_total",
  forbiddenRequestsTotal: "forbidden_requests_total",
  cedcoD02RequestsTotal: "cedco_d02_requests_total",
  voiceCallContractRequestsTotal: "voice_call_contract_requests_total",
  providerBlockedRequestsTotal: "provider_blocked_requests_total",
  policyGateEvaluationsTotal: "policy_gate_evaluations_total",
  policyGateDeniedTotal: "policy_gate_denied_total",
  rateLimitChecksTotal: "rate_limit_checks_total",
  rateLimitDeniedTotal: "rate_limit_denied_total",
  runtimeBlockedRequestsTotal: "runtime_blocked_requests_total",
  workerJobsEnqueuedTotal: "worker_jobs_enqueued_total",
  workerJobsStartedTotal: "worker_jobs_started_total",
  workerJobsSucceededTotal: "worker_jobs_succeeded_total",
  workerJobsFailedTotal: "worker_jobs_failed_total",
  workerJobsDeadLetteredTotal: "worker_jobs_dead_lettered_total",
  workerJobsBlockedTotal: "worker_jobs_blocked_total",
  workerJobDurationMs: "worker_job_duration_ms",
  workerPolicyDeniedTotal: "worker_policy_denied_total",
} as const;
